FROM golang:alpine

RUN apk update && apk add git
RUN go get -t github.com/sirupsen/logrus
RUN go get -t github.com/go-sql-driver/mysql
RUN go get -t github.com/dghubble/go-twitter/twitter
RUN go get -t github.com/dghubble/oauth1
RUN go get -t gopkg.in/robfig/cron.v2


RUN mkdir /apps/

COPY . /apps/
WORKDIR /apps

CMD ["go","run","."]

